# Numpy 실습해보기
---

## Numpy 자체 메소드

1. Array 생성
2. zeros, ones
3. shape

In [1]:
import numpy as np  # Numpy 삽입

### 1. Numpy로 Array 생성하기

Numpy Array는 파이썬의 list와는 달리 C와 같이 데이터 타입을 고정해 만들어야 한다.  
반면, list는 이런 고정 데이터 타입이 아닌 동적 타이핑이 가능하다.
``` python
_list = [True, 3, "3", 3.3] # 동적 타이핑, 타입의 제한이 없음.
```
이러한 리스트가 유연하기 위해서는 리스트의 각 항목에 타입 정보와 참조 횟수, 기타 정보가 들어가야 한다.  
즉, 각 항목이 완전한 파이썬 객체인 것이다.  
모든 변수가 같은 타입인 경우 이 정보가 대부분 불필요하게 중복되므로 고정 타입 배열에 데이터를 저장하는 것이 더 효율적일 수 있다.  

numpy array는 array의 데이터 효율성을 넘어서 연산 또한 가능해 데이터 분석에 용이한 라이브러리다.

In [2]:
# array 생성
arr = np.array([1, 2, 3])

In [3]:
# arr 확인
arr

array([1, 2, 3])

python의 range를 사용할 때처럼 이렇게 배열을 생성할 수도 있다.  

#### Q. 다음 코드를 보며 결과 값이 어떨지 상상하고 코드를 실행해보자.

In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### 2. zeros와 ones
zeros와 ones는 numpy 자체 메소드다.  
각각 0과 1이 채워진 배열이 생성된다. 배열의 길이는 괄호 안의 매개 변수로 결정된다.  
```python
np.zeros(3) #[0., 0., 0.,]
np.ones(3)  #[1., 1., 1.,]
```
각 숫자의 끝에 .이 찍히는 이유는 부동소수점으로 삽입되기 때문이다.  

In [5]:
zeros = np.zeros(5)

In [6]:
# 새로 생긴 zeros 확인
zeros

array([0., 0., 0., 0., 0.])

In [7]:
ones = np.ones(5)

In [8]:
# 새로 생긴 ones 확인
ones

array([1., 1., 1., 1., 1.])

2차원 배열로도 생성할 수 있다.

#### Q. 다음과 같은 출력물이 나오려면 코드를 어떻게 수정해야 할지 생각해보자.

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3. shape으로 배열 확인, reshape으로 배열 변형하기.
shape 또한 numpy 자체 메소드다.  
일차원 배열을 이차원 배열로 변형 할때 많이 쓰이며 1->2가 아닌 역의 상황에서도 사용 가능하다.  
배열의 사이즈만 같다면 다차원으로 자유롭게 변형이 가능하다.
단, 배열의 사이즈가 같지 않을시 오류가 나며 변형이 되지 않으므로 주의가 필요하다.
```python
array([1, 2, 3, 4])
np.reshape(2,3) #오류, 원소의 개수가 6개로 너무 많음
```

In [11]:
arr_shape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  # 원소가 9개인 배열 생성

In [12]:
# 생성된 array 확인
arr_shape

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# arr_shape의 모양 확인
arr_shape.shape

(9,)

In [15]:
# 가로 3, 세로 3의 2차원 배열로 재생성
arr_shape = arr_shape.reshape(3,3)

In [16]:
# 바뀐 array y 확인
arr_shape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 바뀐 array y의 모양 확인
arr_shape.shape

(3, 3)

#### [확인문제] Q. 다음과 같은 배열을 만드시오. (단, reshape을 사용해야함)

In [18]:
# DO NOT WRITE HERE

In [25]:
np_arr = np.ones(15)
np_arr


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np_arr.reshape(5,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Numpy array의 연산
앞서 설명했듯, Numpy Array는 다른 array와는 달리 사칙연산이 가능하다.  
행과 열이 같은 배열을 계산하면 값은 위치에 있는 값들이 계산된다.  
```python
arr_sum = arr_1 + arr_2  #[0, 1, 2] + [1, 2, 3]
arr_sum  #[1, 3, 5]
```
다음 코드를 실행하며 연습해보자.

In [27]:
# 1부터 10까지 정수 배열 생성
arr_1 = np.arange(1, 11)

In [28]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# 10부터 19까지 정수 배열 생성
arr_2 = np.arange(10, 20)

In [30]:
arr_2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
# arr_1과 arr_2를 더한 값을 확인.
# 같은 위치에 있는 값들이 계산된다.
arr_1 + arr_2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [32]:
arr_1 - arr_2

array([-9, -9, -9, -9, -9, -9, -9, -9, -9, -9])

In [33]:
# 피연산자를 주고 단순 사칙연산도 가능
arr_1 + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

#### [확인문제] Q. 다음과 같은 배열을 만드시오.

In [82]:
# DO NOT WRITE HERE

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [34]:
arr1 = np.ones(9)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
arr1 = arr1 * 5

In [38]:
arr1.reshape(3,3)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [39]:
arr2 = np.ones(9)
arr2 = arr2 + 4
arr2.reshape(3,3)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [40]:
arr3 = np.ones((3,3)) + 4
arr3

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])